# Introdução à NumPy
O principal objetivo do NumPy é um array multi-dimensional homogêneo (**ndarray**). É uma tabela de elementos (usualmente números), no qual todos os elementos possuem o mesmo tipo indexados por uma tupla de inteiros não negativos. Em NumPy, as dimensões são chamadas de Axis.

In [3]:
pip install numpy

     --------------------------------------- 14.8/14.8 MB 21.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## 1 Criando Arrays
- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.eye()
- np.asarray()
- np.arange()
- np.linspace()

### 1.1 np.array()

In [6]:
a = np.array([1, 2, 3, 4, 5, 6]) #Cria um array de uma dimensão
print(f'Array de uma dimensão: \n{a}')

Array de uma dimensão: 
[1 2 3 4 5 6]


In [8]:
# Cria um array de 2 dimensões
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f'Array de duas dimensões: \n{b}')

Array de duas dimensões: 
[[1 2 3]
 [4 5 6]]


### 1.2 np.zeros(), np.ones(), np.empty()
Esses métodos são utilizados para a criação de arrays como **Placeholders** (i.e., que serão preenchidos). Para isso, precisamos informar apenas o formato desejaddo. este método evita a necessidade de aumentar as dimensões dos arrays de forma dinâmica, a qual é uma operação custosa.

Portanto, np.zeros(shape=(m,n)) cria um array de mxn preenchidos com 0, enquanto np.ones() preenche o array com 1. Por fim, np.empty() preenche o array com valores aleatórios. É importante destacar que o dtype padrão é float64.

In [10]:
c = np.zeros((2, 2))
print(f'Array preenchidos com zeros: \n {c}')

Array preenchidos com zeros: 
 [[0. 0.]
 [0. 0.]]


In [12]:
d = np.ones((2, 2))
print(f'Array preenchidos com uns: \n {d}')

Array preenchidos com uns: 
 [[1. 1.]
 [1. 1.]]


In [14]:
e = np.empty((2, 2))
print(f'Array preenchidos com qualquer valor alocado na memória: \n {e}')

Array preenchidos com qualquer valor alocado na memória: 
 [[1. 1.]
 [1. 1.]]


### 1.3 np.eye()
cria um ndarray com 1s apenas na diagonal principal

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 1.4 np.asarray()
converte a entrada em um ndarray

In [16]:
f = np.asarray([1, 2, 3, 4, 5, 6])
print(f'Array de uma dimensão: \n{f}')

Array de uma dimensão: 
[1 2 3 4 5 6]


### 1.5 Diferença entre np.array() e np.asarray()
A diferença principal é que o np.array() por padrão cria uma cópia do objeto, enquanto o np.asarray() não cria uma cópia.

In [17]:
a = np.array([1, 2], dtype = np.float32)
print(f'Dados não alterados {np.array(a, dtype=np.float32) is a}')
print(f'Dados alterados {np.array(a, dtype=np.float64) is a}')
print(f'Dados não alterados {np.asarray(a, dtype=np.float32) is a}')
print(f'Dados alterados {np.asarray(a, dtype=np.float64) is a}')

Dados não alterados False
Dados alterados False
Dados não alterados True
Dados alterados False


### 1.6 np.arange()
Este método é utilizado para criar ndarrays com valores dentro de um intervalo definido:

- np.arange(start, stop, step)
  - **start**: valor inicial do intervalo
  - **stop** : valor final do intervalo
  - **step** : espaçamento entre os valores do intervalo

In [18]:
g = np.arange(10, 20, 2)
print(f'O array criado foi: {g}')

O array criado foi: [10 12 14 16 18]


### 1.7 np.linspace()
retorna uma sequencia igualmente espaçada baseada em um intervalo
- np.linspace(start, stop, num=50)

In [19]:
h = np.linspace(0, 99, 10)
print(f'O array criado foi: {h}')

O array criado foi: [ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]


## 2 Atributos importantes de um ndarray
- ndarray.dim
  - representa o número de dimensões do array
- ndarray.shape
  - representa o formato do array
- ndarray.size
  - representa a quantidade total de elementos do array
- ndarray.dtype
  - representa o tipo dos elementos do array
- ndarray.itemsize
  - representa o tamanho em bytes dos elementos do array
- ndarray.data
  - representa os elementos do array

In [22]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

a.shape

(3, 2)

In [23]:
a.size

6

In [24]:
a.ndim

2

In [25]:
a.dtype

dtype('int32')

## 3 Indexando, Fatiando e Iterando arrays
ndarrays podem ser indexados, fatiados (i.e., slicing) e iterados, da mesma forma que as listas em python

### 3.1 Indexando Arrays

In [26]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = a[0][1]
print(f'a: \n{a}')
print(f'b: \n{b}')

a: 
[[1 2]
 [3 4]]
b: 
2


### 3.2 Fatiando Arrays (Slicing)

In [27]:
a = np.arange(20)
print(a[2:10:2])
print(a[2:10])
print(a[2])
print(a[2:])

[2 4 6 8]
[2 3 4 5 6 7 8 9]
2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 4 Alterando o Formato do Array (Reshaping)
altera o formato (i.e., shape) do array sem alterar os dados
- np.reshape(a, newshape)

In [28]:
a = np.arange(6)
b = a.reshape(2, 3)
print(f'a: \n{a}')
print(f'b: \n{b}')

a: 
[0 1 2 3 4 5]
b: 
[[0 1 2]
 [3 4 5]]


## 5 Broadcasting
O termo broadcasting descreve como o NumPy trata arrays com formas diferentes durante operações aritméticas. Sujeito a certas restrições, a matriz menor é "transmitida" pela matriz maior para que tenham formas ccompatíveis. Broadcasting fornece um meio de vetorizar operações de matriz para que o loop ocorra em C em vez de Python. Ele faz isso sem fazer cópias desnecessárias de dados e geralmente leva a implementações de algoritmo eficientes. Há, no entanto, casos em que a transmissão é uma má ideia porque leva ao uso ineficiente da memória que retarda a computação.

As operações NumPy geralmente são feitas em pares de arrays elemento por elemento. No caso mais simples, os dois arrays devem ter exatamente a mesma forma, como no exemplo a seguir:

In [29]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

A regra de transmissão do NumPy relaxa essa restrição quando as formas das matrizes atendem a certas restrições. O exemplo de transmissão mais simples ocorre quando uma matriz e um valor escalar são ccombinados em uma operação:

In [31]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

![Broadcasting](https://numpy.org/doc/stable/_images/broadcasting_1.png)

Ao operar em dois arrays, o NumPy compara suas formas elementarmente. Ele começa com a dimensão à direita (ou seja, mais à direita) e segue para a esquerda. Duas dimensões são compatíveis quando
  - são iguais ou
  - um deles é 1.

Se essas condições não forem atendidas, uma exceção **ValueError: os operandos não puderam ser transmitidos será lançada, indicando que as matrizes têm formas incompatíveis.**

os Arrays de entrada não precisam ter o mesmo número de dimensões. Os arrays resultantes terão o mesmo número de dimensoes que o array de entrada com o maior número de dimensões, onde o tamanho de cada dimensão é o maior da dimensão correspondente entre os arrays de entrada. Observe que as dimensões ausentes são consideradas de tamanho um.

In [32]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
b = np.array([1, 2, 3])
print(a.shape)
print(b.shape)

(3, 3)
(3,)


In [33]:
# Exemplo stretch
np.array([b, b, b])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
c = a + b
print(f'a: \n {a}')
print(f'broadcasting c: \n {c}')

a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
broadcasting c: 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## Funções comuns do NumPy

### 6.1 ndarray.flat()
utilizado para "vetorizar" um array de múltiplas dimensões

In [36]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'a: \n {a}')
print(f'a flat: \n {a.flat[:]}')

a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a flat: 
 [1 2 3 4 5 6 7 8 9]


### 6.2 ndarray.transpose()
faz a transposição dos eixos do array

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 6.3 ndarray.concatenate((a1, a2), axis)

Concatena uma sequencia de arrays baseado no axis especificado

In [40]:
a = np.arange(6).reshape(2,3)
b = np.arange(7, 13).reshape(2, 3)
print(f'a: \n{a}')
print(f'b: \n{b}')

a: 
[[0 1 2]
 [3 4 5]]
b: 
[[ 7  8  9]
 [10 11 12]]


In [41]:
np.concatenate((a, b), axis=0)
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

### 6.4 np.append()
Adiciona valores no final do array, como o .append() das listas python.

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.append(a, [[7, 8, 9]], axis=0) # Axis especifica em qual dimensão
c = np.append(a, [[7, 8, 9]])
print(f'b: \n {b}')
print(f'c: \n {c}')

b: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
c: 
 [1 2 3 4 5 6 7 8 9]


### 6.5 np.insert()
Podemos inserir valores baseado em um axis e um indice
- np.insert(arr, values, axis)

In [43]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.insert(a, 2, [7, 8])

array([0, 1, 7, 8, 2, 3, 4, 5])

In [45]:
np.insert(a, 2, [7, 8], axis=1)

array([[0, 1, 7, 2],
       [3, 4, 8, 5]])

### 6.6 np.delete()
retorna um novo array sem a linha ou a coluna informada

In [46]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
np.delete(a, 0, axis=1)

array([[1, 2],
       [4, 5]])

In [48]:
np.delete(a, 0, axis=0)

array([[3, 4, 5]])

## 7 Operações Aritméticas
- Soma
- subtração
- multiplicação
- divisão
- exponenciação

In [50]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
b = np.arange(10, 16).reshape(2, 3)
b

array([[10, 11, 12],
       [13, 14, 15]])

### 7. 1 Soma

In [53]:
print(np.add(a, b))
print(f'np.add(a, b) == a + b: \n {np.add(a, b) == a + b}')

[[10 12 14]
 [16 18 20]]
np.add(a, b) == a + b: 
 [[ True  True  True]
 [ True  True  True]]


### 7.2 Subtração

In [54]:
a - b

array([[-10, -10, -10],
       [-10, -10, -10]])

### 7.3 Multiplicação

In [55]:
a * b

array([[ 0, 11, 24],
       [39, 56, 75]])

### 7.4 Divisão

In [56]:
a / b

array([[0.        , 0.09090909, 0.16666667],
       [0.23076923, 0.28571429, 0.33333333]])

### 7.5 Dot

In [57]:
np.dot(a, b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [58]:
np.dot(a, b.T)

array([[ 35,  44],
       [134, 170]])

In [60]:
a@b.T

array([[ 35,  44],
       [134, 170]])

## 8 Operações de Agregação
- np.sum()
- np.mean()
- np.std()
- np.var()

In [61]:
array_gigante = np.random.randint(0, 1000, size=1_000_000)

In [62]:
%timeit sum(array_gigante)
%timeit np.sum(array_gigante)

102 ms ± 4.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
705 µs ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### 8.1 np.sum()

In [63]:
np.sum(array_gigante)

499701530

### 8.2 np.mean()

In [64]:
np.mean(array_gigante)

499.70153

### 8.3 np.std()

In [65]:
np.std(array_gigante)

288.5038094820571

### 8.4 np.var()

In [66]:
np.var(array_gigante)

83234.44808565908

### 8.5 np.max()

In [67]:
np.max(array_gigante)

999

### 8.6 np.min()

In [68]:
np.min(array_gigante)

0

## 9 Agregação com multiplas dimensões
podemos utilizar o axis para fazer diferentes agregações

In [70]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

### 9.1 sem axis

In [71]:
np.sum(a)

15

### 9.2 axis = 0

In [72]:
np.sum(a, axis=0)

array([3, 5, 7])

In [74]:
np.sum(a, axis=1)

array([ 3, 12])

In [75]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15])